seed: 0

env:
    job_placing_all_nodes_environment # access registered 'job_placing_all_nodes_environment' custom environment

env_config:
    node_config:
        type_1:
            num_nodes: 16
            workers_config:
                - num_workers: 4
                  worker: ddls.devices.processors.gpus.A100.A100

    topology_config:
        type: torus
        kwargs:
            x_dims: 4
            y_dims: 4

    jobs_config:
        path_to_files: /scratch/datasets/ddls/jobs/tensorflow_synthetic_graphs/valid
        max_files: 1
        job_sampling_mode: remove
        job_interarrival_time_dist:
            _target_: ddls.distributions.uniform.Uniform
            min_val: 1
            max_val: 1000

model:
    custom_model: my_model
    vf_share_layers: True

lr: 0.001

num_gpus: 1
num_workers: 1
framework: torch
