defaults:
    #- epoch_loop: heuristic
    - epoch_loop: rllib

experiment:
    name: job_placing
    seed: 0
    path_to_save: '/scratch/datasets/ddls/sims'

launcher:
     num_epochs: null
     num_episodes: 1
     num_actor_steps: null
     num_eval_episodes: null
     eval_freq: null
     epoch_batch_size: 1
     verbose: True

logger:
    actor_step_log_freq: null
    episode_log_freq: 1
    epoch_log_freq: null
    use_sqlite_database: True

