defaults:
    - environment: job_placing_all_nodes_environment 
    - agent: random_job_placing_agent

experiment:
    name: job_placing
    seed: 0
    path_to_save: '/scratch/datasets/ddls/sims'

launcher:
     num_epochs: null
     num_episodes: 1
     num_actor_steps: null
     num_eval_episodes: null
     eval_freq: null
     epoch_batch_size: null

logger:
    actor_step_log_freq: null
    episode_log_freq: 1
    epoch_log_freq: null
    use_sqlite_database: True

