# ONLY USE FOR VALIDATING HEURISTICS CURRENTLY

eval_loop:
    _target_: ddls.loops.eval_loop.EvalLoop


    env:
        _target_: ddls.environments.ramp_job_placement_shaping.ramp_job_placement_shaping_environment.RampJobPlacementShapingEnvironment

        node_config:
            type_1:
                #num_nodes: 8
                num_nodes: 32
                workers_config:
                    #- num_workers: 4
                    - num_workers: 1
                      worker: ddls.devices.processors.gpus.A100.A100

        topology_config:
            #type: torus
            #kwargs:
                #x_dims: 4
                #y_dims: 4
            type: ramp 
            kwargs:
                num_communication_groups: 4
                num_racks_per_communication_group: 4
                num_servers_per_rack: 2
                num_channels: 1
                channel_bandwidth: 1250000000
                switch_reconfiguration_latency: 0.00000125
                worker_io_latency: 0.000000100

        jobs_config:
            path_to_files: /scratch/datasets/ddls/jobs/pipedream_graphs/image_classification/profiles/alexnet/
            max_files: null
            #replication_factor: 5
            #replication_factor: 10
            #replication_factor: 100
            job_interarrival_time_dist:
                _target_: ddls.distributions.uniform.Uniform
                #min_val: 1
                #max_val: 1000
                min_val: 15000
                max_val: 15000
            job_sampling_mode: remove
            shuffle_files: False
            num_training_steps: 50

        #reward_function: mean_job_completion_time
        reward_function: lookahead_job_completion_time
        reward_function_kwargs:
            fail_reward: job_sequential_completion_time
            fail_reward_factor: 2
            sign: -1
            inverse: false
            #transform_with_log: true
            transform_with_log: false

        op_partitioner: sip_ml_op_partitioner
        op_partitioner_kwargs:
            min_op_run_time_quantum: 0.000006 
            max_partitions_per_op: 2

        op_placer: ramp_first_fit_op_placer

        op_scheduler: srpt_op_scheduler

        dep_placer: first_fit_dep_placer

        dep_scheduler: srpt_dep_scheduler

        pad_obs_kwargs:
            max_nodes: 400


    actor:
        _target_: ddls.environments.ramp_job_placement_shaping.agents.random.Random
        #_target_: ddls.environments.ramp_job_placement_shaping.agents.first_fit.FirstFit
        #_target_: ddls.environments.ramp_job_placement_shaping.agents.last_fit.LastFit




experiment:
    #name: job_placing
    name: ramp_job_placement_shaping
    seed: 1799
    path_to_save: '/scratch/datasets/ddls/sims'
    cuda_visible_devices:
        #- 0
        - 1
        - 2
        - 3



#launcher:
    ##num_epochs: 1
    #num_epochs: 50 # 500
    ##num_epochs: 100 # 500
    #num_episodes: null
    #num_actor_steps: null
    #num_eval_episodes: null
    #eval_freq: null
    #epoch_batch_size: 1
    #verbose: True




#logger:
    #actor_step_log_freq: null
    #episode_log_freq: 2
    #epoch_log_freq: null
    #use_sqlite_database: True




#checkpointer:
    #epoch_checkpoint_freq: 1
