# USE FOR TRAINING AN RLLIB AGENT

defaults:
    - epoch_loop: default
    - env_config: dev
    - eval_config: default
    - model: gnn
    #- algo: apex_dqn
    - algo: impala
    #- algo: ppo
    #- algo: pg
    #- algo: es
    
experiment:
    #name: job_placing
    name: ramp_job_partitioning
    train_seed: 0
    #test_seed: 1799
    test_seed: null
    path_to_save: '/scratch/datasets/ddls/sims'
    cuda_visible_devices:
        - 0
        - 1
        - 2
        - 3
        #- 4
        #- 5
        #- 6
        #- 7
        #- 8
    save_dir: null # placeholder, will be updated

launcher:
    #num_epochs: 1
    #num_epochs: 3
    #num_epochs: 5
    #num_epochs: 10
    #num_epochs: 50 # 500
    #num_epochs: 100 # 500
    #num_epochs: 200 # 500
    #num_epochs: 500 # 500
    num_epochs: 1000
    num_episodes: null
    num_actor_steps: null
    num_eval_episodes: null
    eval_freq: null
    epoch_batch_size: 1
    verbose: True

logger:
    actor_step_log_freq: null
    episode_log_freq: 2
    epoch_log_freq: null
    use_sqlite_database: True

#checkpointer:
    #epoch_checkpoint_freq: 1

wandb:
    init:
        project: ddls
        entity: ong
#wandb: null



