hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task:
    - experiment.seed=0,1
  job:
    name: run_from_config
    override_dirname: experiment.seed=0,1
    id: ???
    num: ???
    config_name: main.yaml
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.1.1
    cwd: /home/zciccwf/phd_project/projects/ddls/scripts
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/zciccwf/phd_project/projects/ddls/scripts/config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    choices:
      agent: random_job_placing_agent
      environment: job_placing_all_nodes_environment
      experiment: job_placing_experiment
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
experiment:
  name: job_placing
  seed: 0
  path_to_save: /scratch/datasets/ddls/sims
environment:
  _target_: ddls.environments.job_placing.job_placing_all_nodes_environment.JobPlacingAllNodesEnvironment
  node_config:
    type_1:
      num_nodes: 16
      workers_config:
      - num_workers: 4
        worker: ddls.devices.processors.gpus.A100.A100
  topology_config:
    type: torus
    kwargs:
      x_dims: 4
      y_dims: 4
  jobs_config:
    path_to_files: /scratch/datasets/ddls/jobs/tensorflow_synthetic_graphs/valid
    max_files: 1
    job_sampling_mode: remove
    job_interarrival_time_dist:
      _target_: ddls.distributions.uniform.Uniform
      min_val: 1
      max_val: 1000
agent:
  _target_: ddls.environments.job_placing.agents.random_job_placing_agent.RandomJobPlacingAgent
  name: Random
